<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Picture;
use Illuminate\Http\Request;

class Animal extends Picture
{
    //
    protected $table = 'animal';

    public function getList(Request $request)
    {
        return parent::getList($request); // TODO: Change the autogenerated stub
    }
}
