<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Picture;

class Animal extends Picture
{
    //
    protected $table = 'animal';

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }
}
