<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Picture;

class Bug extends Picture
{
    //
    protected $table = 'bug';
    public $timestamps = false;

    public function getList($request)
    {
        return parent::getList($request); // TODO: Change the autogenerated stub
    }

}
