<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Picture;

class Bug extends Picture
{
    //
    protected $table = 'bug';

    public function getList()
    {
        return parent::getList(); // TODO: Change the autogenerated stub
    }

}
