<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use App\Models\Picture;

class Fish extends Picture
{
    //
    protected $table = 'fish';
    public $timestamps = false;

    public function getList($request)
    {
        return parent::getList($request); // TODO: Change the autogenerated stub
    }
}
